# Generated by Django 2.1.2 on 2018-11-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Limite_Bairro',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'polls_limite_bairro',
                'managed': False,
            },
        ),
    ]
