# Generated by Django 2.1.2 on 2018-11-09 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(blank=True, max_length=50)),
                ('ultimo_nome', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('aparelho', models.CharField(blank=True, max_length=30)),
                ('ultima_lat', models.CharField(blank=True, max_length=30)),
                ('ultima_long', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
