# Generated by Django 2.1.2 on 2018-11-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aparelho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aparelho', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='aparelho',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ultima_lat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ultima_long',
        ),
        migrations.AddField(
            model_name='aparelho',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Profile'),
        ),
    ]
