# Generated by Django 2.0.8 on 2018-10-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
