# Generated by Django 2.1.2 on 2018-11-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181109_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparelho',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='nome_aparelho',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='ultima_lat',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ultima_long',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Aparelho',
        ),
    ]
