# Generated by Django 2.1.2 on 2018-11-11 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='limite_bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Limite_Bairro'),
        ),
    ]
