# Generated by Django 2.1.2 on 2018-11-11 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_limite_bairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='limite_bairro',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='polls.Limite_Bairro'),
            preserve_default=False,
        ),
    ]
