# Generated by Django 2.1.2 on 2018-11-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_profile_limite_bairro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='limite_bairro',
        ),
    ]
