# Generated by Django 2.1.2 on 2018-10-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20181020_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='primeiro_nome',
        ),
        migrations.AddField(
            model_name='profile',
            name='ultimo_nome',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
