# Generated by Django 2.1.2 on 2018-10-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20181021_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aparelho1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='aparelho2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='aparelho3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
